server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://69.164.197.95:5432/SISCOPE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000 # 30 segundos en milisegundos
      connection-timeout: 5000 # 5 segundos en milisegundos
      max-lifetime: 1800000 # 30 minutos en milisegundos

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  ws:
    version: 1
